name: Debug PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Details
        run: |
          echo "Triggered by issue comment: ${{ github.event.comment.body }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Pull request: ${{ github.event.issue.pull_request }}"
          echo "Pull request number: ${{ github.event.issue.pull_request.number }}"
          echo "Pull request title: ${{ github.event.issue.pull_request.title }}"
          echo "Pull request body: ${{ github.event.issue.pull_request.body }}"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Get PR details
        id: pr
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.issue?.number || context.payload.pull_request?.number;
            if (!prNumber) {
              core.setFailed('Could not determine PR number');
              return;
            }

            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            core.setOutput('branch', pullRequest.head.ref);
            core.setOutput('number', prNumber);
            return pullRequest;

      - name: Create acknowledgment comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ steps.pr.outputs.number }};

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `## 🤖 Merge Bot Activated
              I'm processing your merge request. Here's what I'll do:

              1. ✅ Checkout the PR branch
              2. ✅ Rebase onto main branch
              3. ✅ Setup project dependencies
              4. ✅ Regenerate API client
              5. ✅ Commit any changes if needed
              6. ✅ Merge the PR using squash method

              I'll keep you updated on my progress. Please stand by...`
            });
            
      - name: Checkout PR branch
        run: |
          git fetch origin ${{ steps.pr.outputs.branch }}:${{ steps.pr.outputs.branch }}
          git checkout ${{ steps.pr.outputs.branch }}
      - name: Rebase onto main
        run: |
          git fetch origin main:main
          git rebase main
          if [ $? -ne 0 ]; then
            echo "Rebase failed. There might be conflicts."
            git rebase --abort
            exit 1
          fi
